#!/usr/bin/env python3
"""Reject test, local-state, and private material from an AIPCS wheel."""

from __future__ import annotations

import argparse
from pathlib import Path, PurePosixPath
from zipfile import BadZipFile, ZipFile

DENIED_PARTS = frozenset(
    {
        "__pycache__",
        ".agents",
        ".codex",
        ".data",
        "fakes",
        "fixtures",
        "storage_contracts",
        "tests",
    }
)
DENIED_SUFFIXES = frozenset(
    {".db", ".db3", ".pyc", ".pyo", ".sqlite", ".sqlite3"}
)
DENIED_NAMES = frozenset({"AGENTS.md", "CLAUDE.md"})


def member_violation(name: str) -> str | None:
    relative = PurePosixPath(name)
    folded_parts = {part.casefold() for part in relative.parts}
    if folded_parts & DENIED_PARTS:
        return "test, private, or local-state path"
    if relative.name in DENIED_NAMES:
        return "private operating instruction"
    if relative.suffix.casefold() in DENIED_SUFFIXES:
        return "database or generated bytecode"
    if "conformance" in relative.stem.casefold() or "fake" in relative.stem.casefold():
        return "test-only implementation"
    return None


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("wheel", type=Path)
    args = parser.parse_args()
    if args.wheel.suffix != ".whl" or not args.wheel.is_file():
        parser.error("wheel must be an existing .whl file")
    try:
        with ZipFile(args.wheel) as archive:
            failures = [
                f"{name}: {reason}"
                for name in archive.namelist()
                if (reason := member_violation(name)) is not None
            ]
    except BadZipFile:
        parser.error("wheel must be a valid ZIP archive")
    if failures:
        print("Wheel content check failed:")
        print("\n".join(sorted(failures)))
        return 1
    print("Wheel content check passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
