#!/usr/bin/env python3
"""Reject test, local-state, and private material from an AIPCS release artifact."""

from __future__ import annotations

import argparse
from pathlib import Path, PurePosixPath
from tarfile import ReadError
from tarfile import open as open_tar
from zipfile import BadZipFile, ZipFile

DENIED_PARTS = frozenset(
    {
        "__pycache__",
        ".agents",
        ".codex",
        ".data",
        "fakes",
        "fixtures",
        "storage_contracts",
        "tests",
    }
)
DENIED_SUFFIXES = frozenset({".db", ".db3", ".pyc", ".pyo", ".sqlite", ".sqlite3"})
DENIED_NAMES = frozenset({"AGENTS.md", "CLAUDE.md"})


def member_violation(name: str) -> str | None:
    relative = PurePosixPath(name)
    folded_parts = {part.casefold() for part in relative.parts}
    if folded_parts & DENIED_PARTS:
        return "test, private, or local-state path"
    if relative.name in DENIED_NAMES:
        return "private operating instruction"
    if relative.suffix.casefold() in DENIED_SUFFIXES:
        return "database or generated bytecode"
    if "conformance" in relative.stem.casefold() or "fake" in relative.stem.casefold():
        return "test-only implementation"
    return None


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Check a built wheel or source distribution for private material."
    )
    parser.add_argument("artifact", type=Path, help="path to a .whl or .tar.gz artifact")
    args = parser.parse_args()
    if not args.artifact.is_file():
        parser.error("artifact must be an existing wheel or sdist")
    try:
        if args.artifact.suffix == ".whl":
            with ZipFile(args.artifact) as archive:
                names = archive.namelist()
        elif args.artifact.name.endswith(".tar.gz"):
            with open_tar(args.artifact, "r:gz") as archive:
                names = archive.getnames()
        else:
            parser.error("artifact must be a .whl or .tar.gz")
        failures = [
            f"{name}: {reason}" for name in names if (reason := member_violation(name)) is not None
        ]
    except (BadZipFile, ReadError):
        parser.error("artifact archive is invalid")
    if failures:
        print("Artifact content check failed:")
        print("\n".join(sorted(failures)))
        return 1
    print("Artifact content check passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
