#!/usr/bin/env python3
"""Reject test, local-state, and private material from an AIPCS release artifact."""

from __future__ import annotations

import argparse
import stat
from pathlib import Path, PurePosixPath
from tarfile import ReadError
from tarfile import open as open_tar
from zipfile import BadZipFile, ZipFile, ZipInfo

from check_public_hygiene import content_violations

DENIED_PARTS = frozenset(
    {
        "__pycache__",
        ".agents",
        ".codex",
        ".data",
        ".mypy_cache",
        ".pytest_cache",
        ".ruff_cache",
        "fakes",
        "fixtures",
        "htmlcov",
        "storage_contracts",
        "tests",
        "build",
        "dist",
    }
)
DENIED_SUFFIXES = frozenset({".db", ".db3", ".pyc", ".pyo", ".sqlite", ".sqlite3"})
DENIED_SIDECAR_ENDINGS = ("-journal", "-wal", "-shm")
DENIED_RESIDUE_SUFFIXES = frozenset(
    {".bak", ".orig", ".rej", ".swn", ".swo", ".swp", ".temp", ".tmp"}
)
DENIED_PRIVATE_NAMES = frozenset({"agents.md", "claude.md"})
DENIED_RESIDUE_NAMES = frozenset({".coverage", ".ds_store", "coverage.xml"})
PUBLIC_AGENT_EXAMPLE_SUFFIX = ("examples", "agent-instructions", "AGENTS.md")


def _is_editor_residue(name: str) -> bool:
    return (
        name.endswith("~")
        or name.startswith(".#")
        or (len(name) > 2 and name.startswith("#") and name.endswith("#"))
    )


def member_violation(name: str, *, allow_egg_info: bool) -> str | None:
    relative = PurePosixPath(name)
    if relative.is_absolute() or ".." in relative.parts:
        return "unsafe archive path"
    folded_parts = {part.casefold() for part in relative.parts}
    folded_name = relative.name.casefold()
    if folded_parts & DENIED_PARTS:
        return "test, private, or local-state path"
    is_public_agent_example = relative.parts[-3:] == PUBLIC_AGENT_EXAMPLE_SUFFIX
    if folded_name in DENIED_PRIVATE_NAMES and not is_public_agent_example:
        return "private operating instruction"
    if folded_name in DENIED_RESIDUE_NAMES:
        return "coverage or platform residue"
    if relative.suffix.casefold() in DENIED_SUFFIXES:
        return "database or generated bytecode"
    if folded_name.endswith(DENIED_SIDECAR_ENDINGS):
        return "database sidecar"
    if relative.suffix.casefold() in DENIED_RESIDUE_SUFFIXES or _is_editor_residue(relative.name):
        return "temporary or editor residue"
    if not allow_egg_info and any(part.casefold().endswith(".egg-info") for part in relative.parts):
        return "generated egg-info path"
    if "conformance" in relative.stem.casefold() or "fake" in relative.stem.casefold():
        return "test-only implementation"
    return None


def member_failures(
    name: str,
    data: bytes | None,
    *,
    allow_egg_info: bool,
    regular: bool = True,
) -> list[str]:
    failures: list[str] = []
    if reason := member_violation(name, allow_egg_info=allow_egg_info):
        failures.append(f"{name}: {reason}")
    if not regular:
        failures.append(f"{name}: non-regular archive entry")
    if data is not None:
        failures.extend(
            f"{name}: {reason}" for reason in content_violations(PurePosixPath(name), data)
        )
    return failures


def zip_member_is_regular_or_directory(member: ZipInfo) -> bool:
    if member.is_dir():
        return True
    mode = member.external_attr >> 16
    return stat.S_IFMT(mode) in {0, stat.S_IFREG}


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Check a built wheel or source distribution for private material."
    )
    parser.add_argument("artifact", type=Path, help="path to a .whl or .tar.gz artifact")
    args = parser.parse_args()
    if not args.artifact.is_file():
        parser.error("artifact must be an existing wheel or sdist")
    try:
        failures: list[str] = []
        if args.artifact.suffix == ".whl":
            with ZipFile(args.artifact) as archive:
                for member in archive.infolist():
                    failures.extend(
                        member_failures(
                            member.filename,
                            None if member.is_dir() else archive.read(member),
                            allow_egg_info=False,
                            regular=zip_member_is_regular_or_directory(member),
                        )
                    )
        elif args.artifact.name.endswith(".tar.gz"):
            with open_tar(args.artifact, "r:gz") as archive:
                for member in archive.getmembers():
                    stream = archive.extractfile(member) if member.isfile() else None
                    failures.extend(
                        member_failures(
                            member.name,
                            stream.read() if stream is not None else None,
                            allow_egg_info=True,
                            regular=member.isdir() or member.isfile(),
                        )
                    )
        else:
            parser.error("artifact must be a .whl or .tar.gz")
    except (BadZipFile, ReadError):
        parser.error("artifact archive is invalid")
    if failures:
        print("Artifact content check failed:")
        print("\n".join(sorted(failures)))
        return 1
    print("Artifact content check passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
